version: 0.0
os: linux
files:
  # Copy everything to the EC2 instance (or adjust source if needed)
  - source: /build/
    destination: /var/www/html/

hooks:
  BeforeInstall:
    - location: scripts/install_apache.sh
      timeout: 120
      runas: ec2-user

  AfterInstall:
    - location: scripts/deploy_react.sh
      timeout: 120
      runas: ec2-user

  ApplicationStart:
    - location: scripts/start_apache.sh
      timeout: 120
      runas: ec2-user
